import { Translations, Phrase } from './types';

/* eslint-disable prettier/prettier */
const KOREAN: Translations = {
  [Phrase.NoVideosSaved]: '샘플 텍스트',
  [Phrase.FirstTimeHere]: '샘플 텍스트',
  [Phrase.SetupInstructions]: '샘플 텍스트',
  [Phrase.ClipsDisplayedHere]: '샘플 텍스트',
  [Phrase.NoClipsSaved]: '샘플 텍스트',

  [Phrase.StoragePathDescription]: '샘플 텍스트',
  [Phrase.SeparateBufferPathDescription]: '샘플 텍스트',
  [Phrase.BufferStoragePathDescription]: '샘플 텍스트',
  [Phrase.RetailLogPathDescription]: '샘플 텍스트',
  [Phrase.ClassicLogPathDescription]: '샘플 텍스트',
  [Phrase.EraLogPathDescription]: '샘플 텍스트',
  [Phrase.MaxStorageDescription]: '샘플 텍스트',
  [Phrase.MonitorIndexDescription]: '샘플 텍스트',
  [Phrase.SelectedCategoryDescription]: '샘플 텍스트',
  [Phrase.AudioInputDevicesDescription]: '샘플 텍스트',
  [Phrase.AudioOutputDevicesDescription]: '샘플 텍스트',
  [Phrase.MinEncounterDurationDescription]: '샘플 텍스트',
  [Phrase.StartUpDescription]: '샘플 텍스트',
  [Phrase.StartMinimizedDescription]: '샘플 텍스트',
  [Phrase.ObsOutputResolutionDescription]: '샘플 텍스트',
  [Phrase.ObsFPSDescription]: '샘플 텍스트',
  [Phrase.ObsForceMonoDescription]: '샘플 텍스트',
  [Phrase.ObsQualityDescription]: '샘플 텍스트',
  [Phrase.ObsCaptureModeDescription]: '샘플 텍스트',
  [Phrase.ObsRecEncoderDescription]: '샘플 텍스트',
  [Phrase.RecordRetailDescription]: '샘플 텍스트',
  [Phrase.RecordClassicDescription]: '샘플 텍스트',
  [Phrase.RecordEraDescription]: '샘플 텍스트',
  [Phrase.RecordRaidsDescription]: '샘플 텍스트',
  [Phrase.RecordDungeonsDescription]: '샘플 텍스트',
  [Phrase.RecordTwoVTwoDescription]: '샘플 텍스트',
  [Phrase.RecordThreeVThreeDescription]: '샘플 텍스트',
  [Phrase.RecordFiveVFiveDescription]: '샘플 텍스트',
  [Phrase.RecordSkirmishDescription]: '샘플 텍스트',
  [Phrase.RecordSoloShuffleDescription]: '샘플 텍스트',
  [Phrase.RecordBattlegroundsDescription]: '샘플 텍스트',
  [Phrase.CaptureCursorDescription]: '샘플 텍스트',
  [Phrase.MinKeystoneLevelDescription]: '샘플 텍스트',
  [Phrase.MinRaidDifficultyDescription]: '샘플 텍스트',
  [Phrase.MinimizeOnQuitDescription]: '샘플 텍스트',
  [Phrase.MinimizeToTrayDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayEnabledDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayOwnImageDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayOwnImagePathDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayWidthDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayHeightDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayScaleDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayXPositionDescription]: '샘플 텍스트',
  [Phrase.ChatOverlayYPositionDescription]: '샘플 텍스트',
  [Phrase.SpeakerVolumeDescription]: '샘플 텍스트',
  [Phrase.MicVolumeDescription]: '샘플 텍스트',
  [Phrase.DeathMarkersDescription]: '샘플 텍스트',
  [Phrase.EncounterMarkersDescription]: '샘플 텍스트',
  [Phrase.RoundMarkersDescription]: '샘플 텍스트',
  [Phrase.PushToTalkDescription]: '샘플 텍스트',
  [Phrase.PushToTalkKeyDescription]: '샘플 텍스트',
  [Phrase.PushToTalkMouseButtonDescription]: '샘플 텍스트',
  [Phrase.PushToTalkModifiersDescription]: '샘플 텍스트',
  [Phrase.ObsAudioSuppressionDescription]: '샘플 텍스트',
  [Phrase.RaidOverrunDescription]: '샘플 텍스트',
  [Phrase.DungeonOverrunDescription]: '샘플 텍스트',
  [Phrase.CloudStorageDescription]: '샘플 텍스트',
  [Phrase.CloudUploadDescription]: '샘플 텍스트',
  [Phrase.CloudUploadRateLimitDescription]: '샘플 텍스트',
  [Phrase.CloudUploadRateLimitMbpsDescription]: '샘플 텍스트',
  [Phrase.CloudAccountNameDescription]: '샘플 텍스트',
  [Phrase.CloudAccountPasswordDescription]: '샘플 텍스트',
  [Phrase.CloudGuildNameDescription]: '샘플 텍스트',
  [Phrase.CloudUpload2v2Description]: '샘플 텍스트',
  [Phrase.CloudUpload3v3Description]: '샘플 텍스트',
  [Phrase.CloudUpload5v5Description]: '샘플 텍스트',
  [Phrase.CloudUploadSkirmishDescription]: '샘플 텍스트',
  [Phrase.CloudUploadSoloShuffleDescription]: '샘플 텍스트',
  [Phrase.CloudUploadDungeonsDescription]: '샘플 텍스트',
  [Phrase.CloudUploadRaidsDescription]: '샘플 텍스트',
  [Phrase.CloudUploadBattlegroundsDescription]: '샘플 텍스트',
  [Phrase.CloudUploadRaidMinDifficultyDescription]: '샘플 텍스트',
  [Phrase.CloudUploadDungeonMinLevelDescription]: '샘플 텍스트',
  [Phrase.LanguageDescription]: '샘플 텍스트',
  
  [Phrase.RecordingsHeading]: '샘플 텍스트',
  [Phrase.SettingsHeading]: '샘플 텍스트',
  [Phrase.GeneralButtonText]: '샘플 텍스트',
  [Phrase.SceneButtonText]: '샘플 텍스트',
  [Phrase.Version]: '샘플 텍스트',
  [Phrase.VideoCategoryTwoVTwoLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryThreeVThreeLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryFiveVFiveLabel]: '샘플 텍스트',
  [Phrase.VideoCategorySkirmishLabel]: '샘플 텍스트',
  [Phrase.VideoCategorySoloShuffleLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryMythicPlusLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryRaidsLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryBattlegroundsLabel]: '샘플 텍스트',
  [Phrase.VideoCategoryClipsLabel]: '샘플 텍스트',
  [Phrase.UpdateAvailableTooltip]: '샘플 텍스트',
  [Phrase.LogsButtonLabel]: '샘플 텍스트',
  [Phrase.DiscordButtonLabel]: '샘플 텍스트',
  [Phrase.TestButtonUnable]: '샘플 텍스트',
  
  [Phrase.GeneralSettingsLabel]: '샘플 텍스트',
  [Phrase.DiskStorageFolderLabel]: '샘플 텍스트',
  [Phrase.SeparateBufferFolderLabel]: '샘플 텍스트',
  [Phrase.BufferFolderLabel]: '샘플 텍스트',
  [Phrase.MaxDiskStorageLabel]: '샘플 텍스트',
  [Phrase.WindowsSettingsLabel]: '샘플 텍스트',
  [Phrase.RunOnStartupLabel]: '샘플 텍스트',
  [Phrase.StartMinimizedLabel]: '샘플 텍스트',
  [Phrase.MinimizeOnQuitLabel]: '샘플 텍스트',
  [Phrase.MinimizeToTrayLabel]: '샘플 텍스트',
  [Phrase.LocaleSettingsLabel]: '샘플 텍스트',
  [Phrase.LanguageLabel]: '샘플 텍스트',

  [Phrase.GameSettingsLabel]: '샘플 텍스트',
  [Phrase.RecordRetailLabel]: '샘플 텍스트',
  [Phrase.RetailLogPathLabel]: '샘플 텍스트',
  [Phrase.RecordClassicLabel]: '샘플 텍스트',
  [Phrase.ClassicLogPathLabel]: '샘플 텍스트',
  [Phrase.RecordClassicEraLabel]: '샘플 텍스트',
  [Phrase.ClassicEraLogPathLabel]: '샘플 텍스트',

  [Phrase.PVESettingsLabel]: '샘플 텍스트',
  [Phrase.RecordRaidsLabel]: '샘플 텍스트',
  [Phrase.MinimumEncounterDurationLabel]: '샘플 텍스트',
  [Phrase.RaidOverrunLabel]: '샘플 텍스트',
  [Phrase.MinimumRaidDifficultyLabel]: '샘플 텍스트',
  [Phrase.RecordMythicPlusLabel]: '샘플 텍스트',
  [Phrase.MinimumKeystoneLevelLabel]: '샘플 텍스트',
  [Phrase.MythicPlusOverrunLabel]: '샘플 텍스트',

  [Phrase.PVPSettingsLabel]: '샘플 텍스트',
  [Phrase.Record2v2Label]: '샘플 텍스트',
  [Phrase.Record3v3Label]: '샘플 텍스트',
  [Phrase.Record5v5Label]: '샘플 텍스트',
  [Phrase.RecordSkirmishLabel]: '샘플 텍스트',
  [Phrase.RecordSoloShuffleLabel]: '샘플 텍스트',
  [Phrase.RecordBattlegroundsLabel]: '샘플 텍스트',

  [Phrase.CloudSettingsLabel]: '샘플 텍스트',
  [Phrase.CloudPlaybackLabel]: '샘플 텍스트',
  [Phrase.UserEmailLabel]: '샘플 텍스트',
  [Phrase.PasswordLabel]: '샘플 텍스트',
  [Phrase.GuildNameLabel]: '샘플 텍스트',

  [Phrase.CloudUploadLabel]: '샘플 텍스트',
  [Phrase.UploadRateLimitToggleLabel]: '샘플 텍스트',
  [Phrase.UploadRateLimitValueLabel]: '샘플 텍스트',
  [Phrase.UploadRaidsLabel]: '샘플 텍스트',
  [Phrase.UploadDifficultyThresholdLabel]: '샘플 텍스트',
  [Phrase.UploadMythicPlusLabel]: '샘플 텍스트',
  [Phrase.UploadLevelThresholdLabel]: '샘플 텍스트',
  [Phrase.Upload2v2Label]: '샘플 텍스트',
  [Phrase.Upload3v3Label]: '샘플 텍스트',
  [Phrase.Upload5v5Label]: '샘플 텍스트',
  [Phrase.UploadSkirmishLabel]: '샘플 텍스트',
  [Phrase.UploadSoloShuffleLabel]: '샘플 텍스트',
  [Phrase.UploadBattlgroundsLabel]: '샘플 텍스트',

  [Phrase.SettingsDisabledText]: '샘플 텍스트',
  [Phrase.SomeSettingsDisabledText]: '샘플 텍스트',
  [Phrase.InvalidRetailLogPathText]: '샘플 텍스트',
  [Phrase.InvalidClassicLogPathText]: '샘플 텍스트',
  [Phrase.InvalidClassicEraLogPathText]: '샘플 텍스트',
  [Phrase.CannotBeEmpty]: '샘플 텍스트',
  [Phrase.OneOrGreater]: '샘플 텍스트',

  [Phrase.SourceHeading]: '샘플 텍스트',
  [Phrase.VideoHeading]: '샘플 텍스트',
  [Phrase.AudioHeading]: '샘플 텍스트',
  [Phrase.OverlayHeading]: '샘플 텍스트',

  [Phrase.CaptureModeLabel]: '샘플 텍스트',
  [Phrase.WindowCaptureValue]: '샘플 텍스트',
  [Phrase.GameCaptureValue]: '샘플 텍스트',
  [Phrase.MonitorCaptureValue]: '샘플 텍스트',
  [Phrase.MonitorLabel]: '샘플 텍스트',
  [Phrase.CaptureCursorLabel]: '샘플 텍스트',
  
  [Phrase.FPSLabel]: '샘플 텍스트',
  [Phrase.CanvasResolutionLabel]: '샘플 텍스트',
  [Phrase.QualityLabel]: '샘플 텍스트',
  [Phrase.VideoEncoderLabel]: '샘플 텍스트',

  [Phrase.SpeakersLabel]: '샘플 텍스트',
  [Phrase.MicrophonesLabel]: '샘플 텍스트',
  [Phrase.AudioSuppressionLabel]: '샘플 텍스트',
  [Phrase.MonoInputLabel]: '샘플 텍스트',
  [Phrase.PushToTalkLabel]: '샘플 텍스트',

  [Phrase.ChatOverlayLabel]: '샘플 텍스트',
  [Phrase.OwnImageLabel]: '샘플 텍스트',
  [Phrase.ImagePathLabel]: '샘플 텍스트',
  [Phrase.WidthLabel]: '샘플 텍스트',
  [Phrase.HeightLabel]: '샘플 텍스트',
  [Phrase.HorizontalLabel]: '샘플 텍스트',
  [Phrase.VerticalLabel]: '샘플 텍스트',
  [Phrase.ScaleLabel]: '샘플 텍스트',
};

export default KOREAN;