import { Translations, Phrase } from './phrases';

/* eslint-disable prettier/prettier */
const KOREAN: Translations = {
  [Phrase.NoVideosSaved]: '이 카테고리에 저장된 동영상이 없습니다.',
  [Phrase.FirstTimeHere]: '처음 사용하는 경우 아래 링크에서 설정 방법을 확인할 수 있습니다.',
  [Phrase.SetupInstructions]: 'Setup',
  [Phrase.ClipsDisplayedHere]: '클립한 동영상은 여기에 표시됩니다.',
  [Phrase.NoClipsSaved]: '저장된 클립이 없습니다.',
  [Phrase.StoragePathDescription]: '기록을 저장할 위치. 프로그램이 폴더의 소유권을 가지며, 초기 설정 시 비어 있어야 하며 그 자리에서 내용을 수정해서는 안 됩니다.(영문 폴더명 권장)',
  [Phrase.SeparateBufferPathDescription]: '임시 기록을 별도의 위치에 저장할 수 있도록 설정합니다.',
  [Phrase.BufferStoragePathDescription]: '임시 기록을 저장할 위치. 설정하지 않은 채로 두면 기본 저장 경로에서 관리됩니다.',
  [Phrase.RetailLogPathDescription]: '본섭 로그 폴더 위치 (ex: "World of Warcraft\\_retail_\\Logs")',
  [Phrase.ClassicLogPathDescription]: '클래식 로그 폴더 위치 (ex: "World of Warcraft\\_classic_\\Logs")',
  [Phrase.EraLogPathDescription]: '클래식 시대 로그 폴더 위치 (ex: "World of Warcraft\\_classic_era_\\Logs")',
  [Phrase.MaxStorageDescription]: '저장소 최대 허용 용량. 무제한은 "0"으로 설정. 범위 내로 유지되도록 가장 오래된 기록물은 하나씩 삭제됩니다.',
  [Phrase.MonitorIndexDescription]: '모니터가 여러 대일 경우 개별 항목이 생성되어 기록을 원하는 모니터를 선택할 수 있습니다.',
  [Phrase.SelectedCategoryDescription]: '마지막으로 선택한 동영상 카테고리',
  [Phrase.AudioInputDevicesDescription]: '기록에 포함할 오디오 입력 장치',
  [Phrase.AudioOutputDevicesDescription]: '기록에 포함할 오디오 출력 장치',
  [Phrase.MinEncounterDurationDescription]: '이 시간보다 짧은 전투는 기록되지 않습니다. 이 설정은 보스 리셋이 저장되지 않도록 하는데 목적이 있습니다.',
  [Phrase.StartUpDescription]: '윈도우가 시작될 때 자동으로 프로그램 시작',
  [Phrase.StartMinimizedDescription]: '윈도우 시스템 트레이로 실행',
  [Phrase.ObsOutputResolutionDescription]: '기록물의 해상도. 게임 해상도 크기로 설정 또는 그 이하',
  [Phrase.ObsFPSDescription]: '기록물의 초당 프레임 수. FPS가 낮을수록 동영상 크기는 작아지지만 재생이 원할하지 않습니다.',
  [Phrase.ObsForceMonoDescription]: '입력 장치를 모노로 강제할지 여부. 오디오 마이크가 하나의 스테레오 채널에서만 재생되는 경우 활성화',
  [Phrase.ObsQualityDescription]: '기록물 품질. 높을수록 더 많이 작동하고 더 많은 디스크 공간을 사용합니다.',
  [Phrase.ObsCaptureModeDescription]: '녹화할 때 사용할 모드',
  [Phrase.ObsRecEncoderDescription]: '사용할 비디오 인코더. 일반적으로 하드웨어(Hardware) 인코더 권장',
  [Phrase.RecordRetailDescription]: '본섭을 기록해야 하는지 여부',
  [Phrase.RecordClassicDescription]: '클래식을 기록해야 하는지 여부',
  [Phrase.RecordEraDescription]: '클래식 시대를 기록해야 하는지 여부',
  [Phrase.RecordRaidsDescription]: '레이드를 기록해야 하는지 여부',
  [Phrase.RecordDungeonsDescription]: '쐐기+를 기록해야 하는지 여부',
  [Phrase.RecordTwoVTwoDescription]: '2v2를 기록해야 하는지 여부',
  [Phrase.RecordThreeVThreeDescription]: '3v3을 기록해야 하는지 여부',
  [Phrase.RecordFiveVFiveDescription]: '5v5를 기록해야 하는지 여부',
  [Phrase.RecordSkirmishDescription]: '연습전투를 기록해야 하는지 여부',
  [Phrase.RecordSoloShuffleDescription]: '1인전을 기록해야 하는지 여부',
  [Phrase.RecordBattlegroundsDescription]: '전장을 기록해야 하는지 여부',
  [Phrase.CaptureCursorDescription]: '기록에 커서를 포함할지 여부',
  [Phrase.MinKeystoneLevelDescription]: '기록할 최소 쐐기돌 단수',
  [Phrase.ChallengeModeDescription]: '도전 모드를 기록할지 여부',
  [Phrase.MinRaidDifficultyDescription]: '기록할 최소 레이드 난이도, 본섭만 적용',
  [Phrase.MinimizeOnQuitDescription]: '닫기 버튼이 종료가 아닌 최소화해야 하는지 여부',
  [Phrase.MinimizeToTrayDescription]: '최소화 버튼을 시스템 트레이로 최소화할지 작업 표시줄로 최소화할지 여부',
  [Phrase.ChatOverlayEnabledDescription]: '일부 영역을 가리고 기록하길 원할 때 활성화',
  [Phrase.ChatOverlayOwnImageDescription]: '사용자 지정 이미지를 채팅 오버레이로 사용해야 하는 경우(Pro)',
  [Phrase.ChatOverlayOwnImagePathDescription]: '채팅 오버레이로 사용할 PNG 파일(Pro)',
  [Phrase.ChatOverlayWidthDescription]: '채팅 오버레이 너비',
  [Phrase.ChatOverlayHeightDescription]: '채팅 오버레이 높이',
  [Phrase.ChatOverlayScaleDescription]: '채팅 오버레이 비율',
  [Phrase.ChatOverlayXPositionDescription]: '채팅 오버레이 x-위치',
  [Phrase.ChatOverlayYPositionDescription]: '채팅 오버레이 y-위치',
  [Phrase.SpeakerVolumeDescription]: '녹음 스피커의 볼륨',
  [Phrase.MicVolumeDescription]: '녹음 마이크의 볼륨',
  [Phrase.DeathMarkersDescription]: '타임라인에 표시할 죽음 마크',
  [Phrase.EncounterMarkersDescription]: '타임라인에 표시할 죽음 마크',
  [Phrase.RoundMarkersDescription]: '타임라인에 표시할 죽음 마크',
  [Phrase.PushToTalkDescription]: '단축키를 누르고 있을 때만 녹음해야 하는 경우',
  [Phrase.PushToTalkKeyDescription]: 'PTT 단축키 설정',
  [Phrase.PushToTalkMouseButtonDescription]: 'PTT 마우스 버튼',
  [Phrase.PushToTalkModifiersDescription]: 'PTT 단축키와 함께 필요한 수식어의 쉼표로 구분된 목록',
  [Phrase.PushToTalkReleaseDelayDescription]: 'PTT 키에서 손을 뗀 후 마이크가 활성 상태로 유지되는 시간입니다.',
  [Phrase.ObsAudioSuppressionDescription]: '마이크에 잡히는 배경 소음을 억제하는데 도움이 될 수 있습니다.',
  [Phrase.RaidOverrunDescription]: '보스가 죽은 후 기록할 초과 시간',
  [Phrase.DungeonOverrunDescription]: '던전 완료 후 기록할 초과 시간',
  [Phrase.CloudStorageDescription]: '클라우드 모드 활성화 & 설정',
  [Phrase.CloudUploadDescription]: '클라우드 업로드 모드 활성화 & 설정. 기록이 완료되면 자동으로 클라우드에 업로드되며, 기존 동영상도 수동으로 업로드 할 수 있습니다.',
  [Phrase.CloudUploadRetailDescription]: '본섭 동영상을 클라우드에 업로드해야 하는 경우.',
  [Phrase.CloudUploadClassicDescription]: '클래식 동영상을 클라우드에 업로드해야 하는 경우.',
  [Phrase.CloudUploadRateLimitDescription]: '클라우드 업로드 속도를 제한해야 하는 경우 (업로드가 지연되는 경우 유용)',
  [Phrase.CloudUploadRateLimitMbpsDescription]: '업로드 속도 제한 (MB/s)',
  [Phrase.CloudAccountNameDescription]: '계정 이름',
  [Phrase.CloudAccountPasswordDescription]: '계정 비밀번호',
  [Phrase.CloudGuildNameDescription]: '서버 이름',
  [Phrase.CloudUpload2v2Description]: '2v2를 업로드해야 하는 경우',
  [Phrase.CloudUpload3v3Description]: '3v3을 업로드해야 하는 경우',
  [Phrase.CloudUpload5v5Description]: '5v5를 업로드해야 하는 경우',
  [Phrase.CloudUploadSkirmishDescription]: '연습전투를 업로드해야 하는 경우',
  [Phrase.CloudUploadSoloShuffleDescription]: '1인전을 업로드해야 하는 경우',
  [Phrase.CloudUploadDungeonsDescription]: '쐐기+를 업로드해야 하는 경우',
  [Phrase.CloudUploadRaidsDescription]: '레이드를 업로드해야 하는 경우',
  [Phrase.CloudUploadBattlegroundsDescription]: '전장을 업로드해야 하는 경우',
  [Phrase.CloudUploadRaidMinDifficultyDescription]: '업로드할 최소 레이드 난이도',
  [Phrase.CloudUploadDungeonMinLevelDescription]: '업로드할 최소 쐐기돌 단수',
  [Phrase.LanguageDescription]: '프로그램에서 사용할 언어',
  [Phrase.RecordingsHeading]: 'Recordings',
  [Phrase.SettingsHeading]: 'Settings',
  [Phrase.GeneralButtonText]: '설정',
  [Phrase.SceneButtonText]: '화면 설정',
  [Phrase.Version]: 'Version',
  [Phrase.VideoCategoryTwoVTwoLabel]: '2v2',
  [Phrase.VideoCategoryThreeVThreeLabel]: '3v3',
  [Phrase.VideoCategoryFiveVFiveLabel]: '5v5',
  [Phrase.VideoCategorySkirmishLabel]: '연습전투',
  [Phrase.VideoCategorySoloShuffleLabel]: '1인전',
  [Phrase.VideoCategoryMythicPlusLabel]: '쐐기+',
  [Phrase.VideoCategoryRaidsLabel]: '레이드',
  [Phrase.VideoCategoryBattlegroundsLabel]: '전장',
  [Phrase.VideoCategoryClipsLabel]: '클립',
  [Phrase.LogsButtonLabel]: 'Folder',
  [Phrase.DiscordButtonLabel]: 'Setup',
  [Phrase.TestButtonUnable]: '지금은 테스트를 실행할 수 없습니다. 테스트를 실행하려면 게임이 실행 중이어야 하고, 설정이 유효해야 하며 현재 활동 중이 아니어야 합니다.',
  [Phrase.GeneralSettingsLabel]: '일반 설정',
  [Phrase.DiskStorageFolderLabel]: '디스크 저장 폴더',
  [Phrase.SeparateBufferFolderLabel]: '별도의 임시 폴더',
  [Phrase.BufferFolderLabel]: '임시 폴더',
  [Phrase.MaxDiskStorageLabel]: '디스크 저장 용량 제한 (GB)',
  [Phrase.WindowsSettingsLabel]: '윈도우 설정',
  [Phrase.RunOnStartupLabel]: '시작시 실행',
  [Phrase.StartMinimizedLabel]: '트레이 시작',
  [Phrase.MinimizeOnQuitLabel]: '종료시 트레이',
  [Phrase.MinimizeToTrayLabel]: '최소화 트레이',
  [Phrase.LocaleSettingsLabel]: '언어 설정',
  [Phrase.LanguageLabel]: '언어',
  [Phrase.GameSettingsLabel]: '게임 설정',
  [Phrase.RecordRetailLabel]: '본섭 기록',
  [Phrase.RetailLogPathLabel]: '본섭 로그 경로',
  [Phrase.RecordClassicLabel]: '클래식 기록',
  [Phrase.ClassicLogPathLabel]: '클래식 로그 경로',
  [Phrase.RecordClassicEraLabel]: '클래식 시대 기록',
  [Phrase.ClassicEraLogPathLabel]: '클래식 시대 로그 경로',
  [Phrase.PVESettingsLabel]: 'PvE 설정',
  [Phrase.RecordRaidsLabel]: '레이드 기록',
  [Phrase.MinimumEncounterDurationLabel]: '최소 전투 시간 (초)',
  [Phrase.RaidOverrunLabel]: '레이드 오버런 (초)',
  [Phrase.MinimumRaidDifficultyLabel]: '최소 레이드 난이도',
  [Phrase.RecordMythicPlusLabel]: '쐐기+ 기록',
  [Phrase.MinimumKeystoneLevelLabel]: '최소 쐐기돌 단수',
  [Phrase.ChallengeModeLabel]: '도전 모드 기록',
  [Phrase.MythicPlusOverrunLabel]: '쐐기+ 오버런 (초)',
  [Phrase.PVPSettingsLabel]: 'PvP 설정',
  [Phrase.Record2v2Label]: '2v2 기록',
  [Phrase.Record3v3Label]: '3v3 기록',
  [Phrase.Record5v5Label]: '5v5 기록',
  [Phrase.RecordSkirmishLabel]: '연습전투 기록',
  [Phrase.RecordSoloShuffleLabel]: '1인전 기록',
  [Phrase.RecordBattlegroundsLabel]: '전장 기록',
  [Phrase.CloudSettingsLabel]: '클라우드 설정',
  [Phrase.CloudPlaybackLabel]: '클라우드 모드',
  [Phrase.UserEmailLabel]: '아이디',
  [Phrase.PasswordLabel]: '비밀번호',
  [Phrase.GuildNameLabel]: '서버',
  [Phrase.CloudUploadLabel]: '클라우드 업로드',
  [Phrase.CloudUploadRetailLabel]: '본섭 업로드',
  [Phrase.CloudUploadClassicLabel]: '클래식 업로드',
  [Phrase.UploadRateLimitToggleLabel]: '업로드 속도 제한',
  [Phrase.UploadRateLimitValueLabel]: '업로드 속도 제한 (MB/s)',
  [Phrase.UploadRaidsLabel]: '레이드 업로드',
  [Phrase.UploadDifficultyThresholdLabel]: '업로드 최소 난이도',
  [Phrase.UploadMythicPlusLabel]: '쐐기+ 업로드',
  [Phrase.UploadLevelThresholdLabel]: '업로드 최소 단수',
  [Phrase.Upload2v2Label]: '2v2 업로드',
  [Phrase.Upload3v3Label]: '3v3 업로드',
  [Phrase.Upload5v5Label]: '5v5 업로드',
  [Phrase.UploadSkirmishLabel]: '연습전투 업로드',
  [Phrase.UploadSoloShuffleLabel]: '1인전 업로드',
  [Phrase.UploadBattlgroundsLabel]: '전장 업로드',
  [Phrase.SettingsDisabledText]: '기록이 활성화된 동안에는 이러한 설정을 수정할 수 없습니다.',
  [Phrase.SomeSettingsDisabledText]: '기록이 활성화되어 있는 동안에는 일부 설정을 수정할 수 없습니다.',
  [Phrase.CloudSettingsDisabledText]: '클라우드 설정은 업로드 또는 다운로드가 진행 중일 때 수정할 수 없습니다.',
  [Phrase.InvalidRetailLogPathText]: '잘못된 본섭 로그 경로',
  [Phrase.InvalidClassicLogPathText]: '잘못된 클래식 로그 경로',
  [Phrase.InvalidClassicEraLogPathText]: '잘못된 클래식 시대 로그 경로',
  [Phrase.CannotBeEmpty]: '비워둘 수 없습니다.',
  [Phrase.OneOrGreater]: '1 이상이어야 합니다.',
  [Phrase.SourceHeading]: '소스',
  [Phrase.VideoHeading]: '비디오',
  [Phrase.AudioHeading]: '오디오',
  [Phrase.OverlayHeading]: '오버레이',
  [Phrase.CaptureModeLabel]: '녹화 모드',
  [Phrase.WindowCaptureValue]: '윈도우',
  [Phrase.GameCaptureValue]: '게임',
  [Phrase.MonitorCaptureValue]: '모니터',
  [Phrase.MonitorLabel]: '모니터',
  [Phrase.CaptureCursorLabel]: '커서 포함',
  [Phrase.FPSLabel]: 'FPS',
  [Phrase.CanvasResolutionLabel]: '화면 해상도',
  [Phrase.QualityLabel]: '품질',
  [Phrase.VideoEncoderLabel]: '비디오 인코더',
  [Phrase.SpeakersLabel]: '스피커',
  [Phrase.MicrophonesLabel]: '마이크',
  [Phrase.AudioSuppressionLabel]: '오디오 억제',
  [Phrase.MonoInputLabel]: 'Mono Input',
  [Phrase.PushToTalkLabel]: 'PTT',
  [Phrase.PushToTalkKeyLabel]: 'PTT Key',
  [Phrase.PressAnyKeyCombination]: '키 조합을 누르세요..',
  [Phrase.ClickToBind]: '조합하려면 클릭',
  [Phrase.ClickToRebind]: '다시 조합하려면 클릭',
  [Phrase.Mouse]: 'Mouse',
  [Phrase.ChatOverlayLabel]: '채팅 오버레이',
  [Phrase.OwnImageLabel]: '지정 이미지',
  [Phrase.ImagePathLabel]: '이미지 경로',
  [Phrase.WidthLabel]: '너비',
  [Phrase.HeightLabel]: '높이',
  [Phrase.HorizontalLabel]: '가로 위치',
  [Phrase.VerticalLabel]: '세로 위치',
  [Phrase.ScaleLabel]: '스케일',
  [Phrase.TableHeaderEncounter]: 'Encounter',
  [Phrase.TableHeaderResult]: 'Result',
  [Phrase.TableHeaderPull]: 'Pull',
  [Phrase.TableHeaderDifficulty]: 'Difficulty',
  [Phrase.TableHeaderDuration]: 'Duration',
  [Phrase.TableHeaderDate]: 'Date',
  [Phrase.TableHeaderViewpoints]: 'Viewpoints',
  [Phrase.TableHeaderMap]: 'Map',
  [Phrase.TableHeaderType]: 'Type',
  [Phrase.TableHeaderTag]: 'Tag',
  [Phrase.SearchLabel]: '검색',
  [Phrase.SearchSuggestionMythicPlus]: 'Search',
  [Phrase.SearchSuggestionRaid]: 'Search',
  [Phrase.SearchSuggestionBattlegrounds]: 'Search',
  [Phrase.SearchSuggestionSoloShuffle]: 'Search',
  [Phrase.SearchSuggestionDefault]: 'Search',
  [Phrase.ShowRoundsLabel]: '라운드 표시',
  [Phrase.ShowDeathsLabel]: '죽음 표시',
  [Phrase.ShowEncountersLabel]: '보스 표시',
  [Phrase.FullScreenTooltip]: '전체 화면',
  [Phrase.PlaybackSpeedTooltip]: '재생 속도',
  [Phrase.ClipTooltip]: '클립',
  [Phrase.ClipUnavailableTooltip]: '디스크에 저장된 동영상만 클립할 수 있습니다.',
  [Phrase.ConfirmTooltip]: '확인',
  [Phrase.CancelTooltip]: '취소',
  [Phrase.TagButtonTooltip]: '태그',
  [Phrase.StarButtonTooltip]: '북마크 켜기',
  [Phrase.UnstarButtonTooltip]: '북마크 끄기',
  [Phrase.OpenFolderButtonTooltip]: '저장 폴더 열기',
  [Phrase.DeleteButtonTooltip]: '삭제',
  [Phrase.BulkDeleteButtonTooltip]: '선택한 행 삭제',
  [Phrase.ShareLinkButtonTooltip]: '공유 가능한 링크 받기',
  [Phrase.CloudButtonTooltip]: '클라우드에 저장됨',
  [Phrase.DiskButtonTooltip]: '디스크에 저장됨',
  [Phrase.UploadButtonTooltip]: '클라우드에 업로드',
  [Phrase.DownloadButtonTooltip]: '디스크에 다운로드',
  [Phrase.StatusTitleRecording]: '녹화 중',
  [Phrase.StatusTitleWaiting]: '대기 중',
  [Phrase.StatusTitleInvalid]: '잘못된 구성',
  [Phrase.StatusTitleReady]: '녹화 준비 완료',
  [Phrase.StatusTitleFatalError]: '오류 발생',
  [Phrase.StatusTitleOverrunning]: '오버런 중',
  [Phrase.StatusTitleReconfiguring]: '대기 중',
  [Phrase.StatusDescriptionRecording]: '현재 기록 중입니다.',
  [Phrase.StatusDescriptionForceEnd]: '기록을 강제로 종료할 수 있습니다. 일반적으로 이 선택은 필요하지 않습니다. 실패한 쐐기+를 강제 종료하는 데 도움이 될 수 있습니다.',
  [Phrase.StatusDescriptionWaiting]: '게임이 시작되기를 기다리는 중.',
  [Phrase.StatusDescriptionConfiguredToRecord]: '프로그램이 녹화하도록 구성되었습니다.',
  [Phrase.StatusDescriptionMisconfigured]: '프로그램이 잘못 구성되었습니다.',
  [Phrase.StatusDescriptionResolveError]: '아래 오류를 해결하세요.',
  [Phrase.StatusDescriptionDetectedRunning]: '게임이 실행 중임을 감지했습니다.',
  [Phrase.StatusDescriptionWatchingLogs]: '기록 가능한 이벤트가 전투 로그에 나타나기를 기다리고 있습니다.',
  [Phrase.StatusDescriptionTip]: 'Tip',
  [Phrase.StatusDescriptionIfNoRecording]: '기록이 시작되지 않으면 게임 내 로그 애드온 설정을 확인하고 로그 경로 구성이 올바른지 확인하세요.',
  [Phrase.StatusDescriptionFatalError]: '치명적인 오류가 발생했습니다.',
  [Phrase.StatusDescriptionPleaseResolve]: '아래 오류를 해결한 후 프로그램을 다시 시작하세요.',
  [Phrase.StatusDescriptionIfRecurring]: '이 문제가 반복되면 재설치 또는 도움을 요청하세요.',
  [Phrase.StatusDescriptionOverrunning]: '기록 활동이 성공적으로 완료되었음을 감지했습니다. 기록을 파악하기 위해 몇 초 더 필요합니다.',
  [Phrase.StatusDescriptionNothing]: '아무것도 없습니다. 설정에서 게임 모드를 활성화할 수 있습니다.',
  [Phrase.StatusHeading]: 'Status',
  [Phrase.StatusButtonForceEndLabel]: '강제 중지',
  [Phrase.Retail]: '본섭',
  [Phrase.Classic]: '클래식',
  [Phrase.Era]: '시대',
  [Phrase.MicListeningTooltip]: 'Listening',
  [Phrase.MicMutedTooltip]: 'Muted',
  [Phrase.CrashHappenedText]: 'OBS 충돌이 발생하여 복구되었습니다. 정상적인 작동에서는 이런 일이 일어나지 않아야 합니다.',
  [Phrase.SettingsPageApplicationHeader]: 'Application',
  [Phrase.SettingsPageGameHeader]: 'Game',
  [Phrase.SettingsPageProHeader]: 'Pro',
  [Phrase.TestButtonHeading]: '테스트할 카테고리를 선택하세요',
  [Phrase.SystemTrayOpen]: '열기',
  [Phrase.SystemTrayQuit]: '종료',
  [Phrase.Kill]: '킬',
  [Phrase.Wipe]: '전멸',
  [Phrase.Win]: '승리',
  [Phrase.Loss]: '패배',
  [Phrase.Abandoned]: '탈주',
  [Phrase.Depleted]: '소진',
  [Phrase.AreYouSure]: '확실하신가요?',
  [Phrase.ThisWillPermanentlyDelete]: '이렇게 하면 영구적으로 삭제됩니다.',
  [Phrase.Recordings]: '기록물',
  [Phrase.From]: '/',
  [Phrase.Rows]: '행',
  [Phrase.Death]: '죽음',
  [Phrase.AddADescription]: '태그 추가',
  [Phrase.TagDialogText]: '이 기록은 검색창에서 조회할 수 있습니다.',
  [Phrase.Clear]: '삭제',
  [Phrase.Save]: '저장',
  [Phrase.ShareableLinkTitle]: '공유할 수 있는 링크가 클립보드에 저장됐습니다.',
  [Phrase.ShareableLinkText]: '이 링크는 동영상이 클라우드에 저장되어 있는 동안 유효합니다.',
  [Phrase.ShareableLinkFailedTitle]: '링크 생성에 실패했습니다.',
  [Phrase.ShareableLinkFailedText]: '다시 시도해 보세요.',
  [Phrase.CloudUsageDescription]: '클라우드 사용량',
  [Phrase.DiskUsageDescription]: '디스크 사용량',
  [Phrase.Hardware]: 'Hardware',
  [Phrase.Software]: 'Software',
  [Phrase.All]: '전체',
  [Phrase.Own]: '자신',
  [Phrase.None]: '없음',
  [Phrase.On]: 'On',
  [Phrase.Off]: 'Off',
  [Phrase.Ultra]: '매우 높음',
  [Phrase.High]: '높음',
  [Phrase.Moderate]: '보통',
  [Phrase.Low]: '낮음',
  [Phrase.LFR]: '공격대 찾기',
  [Phrase.Normal]: '일반',
  [Phrase.Heroic]: '영웅',
  [Phrase.Mythic]: '신화',
  [Phrase.Pvp]: 'PVP',
  [Phrase.ErrorAccountEmpty]: '계정 아이디는 비워둘 수 없습니다.',
  [Phrase.ErrorPasswordEmpty]: '계정 비밀번호는 비워둘 수 없습니다.',
  [Phrase.ErrorGuildEmpty]: '서버 이름은 비워둘 수 없습니다.',
  [Phrase.ErrorUserNotAuthorizedPlayback]: '클라우드에 접근할 수 있는 권한이 없습니다.',
  [Phrase.ErrorUserNotAuthorizedUpload]: '클라우드에 업로드할 수 있는 권한이 없습니다.',
  [Phrase.ErrorStoragePathInvalid]: '저장 경로가 잘못되었습니다.',
  [Phrase.ErrorBufferPathInvalid]: '임시 저장 경로가 잘못되었습니다.',
  [Phrase.ErrorStoragePathSameAsBufferPath]: '저장 경로가 임시 경로와 동일합니다.',
  [Phrase.ErrorCustomOverlayNotAllowed]: '사용자 지정 오버레이를 사용하려면 클라우드 모드를 사용 설정하세요.',
  [Phrase.ErrorNoCustomImage]: '사용자 지정 오버레이 이미지 경로가 지정되지 않았습니다.',
  [Phrase.ErrorCustomImageFileType]: '오버레이 이미지는 .png 또는 .gif 파일이어야 합니다.',
  [Phrase.ErrorCustomImageNotExist]: '지정한 파일이 존재하지 않습니다.',
  [Phrase.InvalidRetailLogPath]: '잘못된 본섭 로그 경로',
  [Phrase.InvalidClassicLogPath]: '잘못된 클래식 로그 경로',
  [Phrase.InvalidEraLogPath]: '잘못된 시대 로그 경로',
  [Phrase.SelectAnOutputDevice]: '출력 장치 선택',
  [Phrase.SelectAnInputDevice]: '입력 장치 선택',
  [Phrase.ClickToSelectAll]: '모두 선택하려면 클릭',
  [Phrase.ClickToSortAsc]: '오름차순으로 정렬하려면 클릭',
  [Phrase.ClickToSortDec]: '내림차순으로 정렬하려면 클릭',
  [Phrase.ClickToClearSort]: '정렬을 지우려면 클릭',
  [Phrase.Start]: '시작',
  [Phrase.End]: '끝',
  [Phrase.Cloud]: "클라우드",
  [Phrase.Disk]: "디스크",
  [Phrase.Starred]: "북마크",
  [Phrase.NotStarred]: "잠금 해제됨",
  [Phrase.Tagged]: "태그",
  [Phrase.Today]: "오늘",
  [Phrase.Yesterday]: "어제",
  [Phrase.Chests]: "상자",
  [Phrase.Timed]: "소진",
  [Phrase.Activity]: "활동",
  [Phrase.Unknown]: "알 수 없음",
  [Phrase.NoneTagged]: "이 행에는 태그가 지정된 기록이 없습니다.",
  [Phrase.MultipleTagged]: "이 행에는 태그가 지정된 기록이 여러 개 포함되어 있습니다.",
  [Phrase.NoneStarred]: "이 행은 잠겨 있지 않습니다. 기록이 오래되면 자동 삭제될 수 있습니다.",
  [Phrase.SomeStarred]: '이 행은 잠겨 있습니다. 자동으로 삭제되지 않습니다.',
  [Phrase.UploadClipsLabel]: '클립 업로드',
  [Phrase.CloudUploadClipsDescription]: '클립을 업로드해야 하는 경우',
  [Phrase.RetailPtrLogPathDescription]: '본섭 PTR 로그 폴더 위치 (ex: "World of Warcraft\\_xptr_\\Logs")',
  [Phrase.RecordRetailPtrDescription]: '본섭 PTR을 기록해야 하는지 여부',
  [Phrase.RetailPtr]: '본섭 PTR',
  [Phrase.RecordRetailPtrLabel]: '본섭 PTR 기록',
  [Phrase.RetailPtrLogPathLabel]: '본섭 PTR 로그 경로',
  [Phrase.InvalidRetailPtrLogPathText]: '잘못된 본섭 PTR 로그 경로',
  [Phrase.Details]: 'Details',
  [Phrase.PlayerModeLabel]: '플레이어 모드',
  [Phrase.MultiPlayerModeHeading]: '멀티플레이어 모드',
  [Phrase.MultiPlayerModeAdvice1]: '왼쪽의 그리드를 사용하여 최대 4명의 플레이어를 한 번에 선택/선택 해제할 수 있습니다.',
  [Phrase.MultiPlayerModeAdvice2]: '여기에 일반적으로 표시되는 버튼을 복원하려면 싱글 플레이어 모드로 돌아가세요.',
  [Phrase.UpdateAvailableTooltip]: '업데이트가 있습니다. 클릭하여 설치하세요.',
  [Phrase.UpdateAvailableTitle]: '업데이트 가능',
  [Phrase.UpdateAvailableText]: '사용 가능한 업데이트가 있으며 설치할 준비가 되었습니다.',
  [Phrase.UpdateAvailableInstallButtonText]: '지금 설치',
  [Phrase.UpdateAvailableRemindButtonText]: '나중에 알림',
  [Phrase.Saving]: '저장...',
  [Phrase.StartTyping]: '검색...',
  [Phrase.ToggleDrawingMode]: '그리기 모드',
  [Phrase.StarSelected]: '선택한 행 잠금',
  [Phrase.UnstarSelected]: '선택한 행 잠금 해제',
  [Phrase.Selection]: '선택 옵션',
  [Phrase.NoCombatants]: '전투원 데이터가 없습니다.',
  [Phrase.DateFilter]: "날짜 필터",
  [Phrase.DateFilterSeparator]: "~",
  [Phrase.Last7Days]: "최근 7일",
  [Phrase.Last30Days]: "최근 30일",
  [Phrase.ThisMonth]: "이번 달",
  [Phrase.LastMonth]: "지난 달",
  [Phrase.Cancel]: "취소",
  [Phrase.Apply]: "적용",
  [Phrase.January]: "1월",
  [Phrase.February]: "2월",
  [Phrase.March]: "3월",
  [Phrase.April]: "4월",
  [Phrase.May]: "5월",
  [Phrase.June]: "6월",
  [Phrase.July]: "7월",
  [Phrase.August]: "8월",
  [Phrase.September]: "9월",
  [Phrase.October]: "10월",
  [Phrase.November]: "11월",
  [Phrase.December]: "12월",
  [Phrase.Sunday]: "일",
  [Phrase.Monday]: "월",
  [Phrase.Tuesday]: "화",
  [Phrase.Wednesday]: "수",
  [Phrase.Thursday]: "목",
  [Phrase.Friday]: "금",
  [Phrase.Saturday]: "토",
  [Phrase.PermissionLabel]: "권한",
  [Phrase.PermissionDescription]: "관리자가 부여한 현재 선택된 서버 내 접근 권한 수준입니다.",
  [Phrase.PermissionReadLabel]: "읽기",
  [Phrase.PermissionReadDescription]: "영상 재생을 허용합니다.",
  [Phrase.PermissionWriteLabel]: "쓰기",
  [Phrase.PermissionWriteDescription]: "영상 업로드, 태그 지정, 잠금을 허용합니다.",
  [Phrase.PermissionDeleteLabel]: "삭제",
  [Phrase.PermissionDeleteDescription]: "영상 삭제 및 잠금 해제를 허용합니다.",
  [Phrase.ButtonDiskOnlyDescription]: "사용자는 구성된 서버에 대한 접근 권한이 제한되어 있습니다. 디스크 동영상에만 선택 옵션을 적용하고, 클라우드 동영상과 관련 서버 접근 권한은 무시합니다.",
  [Phrase.StorageFilterLabel]: "저장소 필터",
  [Phrase.ShowDiskOnlyTooltip]: "디스크 동영상만 표시",
  [Phrase.ShowCloudOnlyTooltip]: "클라우드 동영상만 표시",
  [Phrase.ShowBothTooltip]: "디스크 및 클라우드 동영상을 그룹화하고 모든 동영상을 표시합니다.",
  [Phrase.GuildNoPermission]: "이 작업을 수행하기 위한 권한이 없습니다.",
  [Phrase.RemoveTagFromList]: "목록에서 %value%를 제거합니다.",
  [Phrase.DownloadUploadDisabledDueToFilter]: "현재 선택한 저장소 필터로 인해 비활성화되었습니다.",
  [Phrase.ProcessesLabel]: "응용 프로그램",
  [Phrase.SelectProcess]: "응용 프로그램 선택",
  [Phrase.AudioProcessDevicesDescription]: "선택한 스피커와 마이크 외에 오디오를 포함할 응용 프로그램",
  [Phrase.ProcessVolumeDescription]: "기록에서 응용 프로그램의 볼륨은 0에서 1까지입니다.",
  [Phrase.HideEmptyCategoriesLabel]: "빈 카테고리 숨기기",
  [Phrase.HideEmptyCategoriesDescription]: "비디오가 없는 카테고리를 숨깁니다.",
  [Phrase.HardwareAccelerationLabel]: "하드웨어 가속",
  [Phrase.HardwareAccelerationDescription]: "프로그램의 하드웨어 가속 렌더링을 활성화합니다. 이 기능은 대부분의 사용자에게 권장되며, 특히 AV1 인코딩을 사용하는 경우에 유용하지만 일부 시스템에서는 문제가 발생할 수 있습니다. 이 변경 사항은 프로그램을 재시작해야 적용됩니다.",
  [Phrase.RecordCurrentRaidsOnlyLabel]: "현재 시즌 레이드만",
  [Phrase.RecordCurrentRaidsOnlyDescription]: "현재 시즌의 레이드 전투만 기록합니다. 이는 본섭 레이드 전투에만 적용됩니다.",
  [Phrase.UploadCurrentRaidsOnlyLabel]: "현재 시즌 레이드만",
  [Phrase.UploadCurrentRaidsOnlyDescription]: "현재 시즌의 레이드 전투만 업로드합니다. 이는 본섭 레이드 전투에만 적용됩니다.",
  [Phrase.MustNotBeEmpty]: "비워둘 수 없습니다",
  [Phrase.PushToTalkReleaseDelayLabel]: "종료 지연",
  [Phrase.ForceSdrLabel]: "SDR 강제",
  [Phrase.ForceSdrDescription]: "HDR 대신 SDR로 영상을 강제로 렌더링합니다.",
  [Phrase.VideoSourceScaleDescription]: "비디오 소스의 비율.",
  [Phrase.VideoSourceXPositionDescription]: "비디오 소스의 X 좌표.",
  [Phrase.VideoSourceYPositionDescription]: "비디오 소스의 Y 좌표.",
  [Phrase.VideoCategoryManualLabel]: '수동',
  [Phrase.ManualRecordSettingsLabel]: '수동 녹화 설정',
  [Phrase.ManualRecordSwitchLabel]: '수동 녹화',
  [Phrase.ManualRecordHotKeyLabel]: '시작/중지 단축키',
  [Phrase.ManualRecordUploadLabel]: '수동 녹화 업로드',
  [Phrase.ManualRecordDescription]: '전투 로그에 기록되지 않는 상황을 사용자가 직접 시작하고 중지하여 녹화할 수 있습니다.',
  [Phrase.ManualRecordHotKeyDescription]: '수동 녹화를 시작하거나 중지할 단축키를 설정합니다.',
  [Phrase.ManualRecordUploadDescription]: '수동으로 시작한 녹화를 자동으로 클라우드에 업로드합니다.',
  [Phrase.ManualRecordSoundAlertLabel]: '소리 알림',
  [Phrase.ManualRecordSoundAlertDescription]: '수동 녹화가 시작되거나 중지될 때 소리 알림을 재생합니다.',
  [Phrase.StatusTitleRec]: 'Rec',
  [Phrase.StatusTitlePro]: 'Pro',
  [Phrase.StatusTitleConnected]: '연결됨',
  [Phrase.StatusDescrConnected]: '연결이 완료되었습니다. 기능이 활성화되었습니다.',
  [Phrase.StatusTitleDisconnected]: '연결 해제',
  [Phrase.StatusDescrDisconnected]: '기능을 사용하려면 구독 또는 서버에 가입한 뒤 설정 페이지에서 로그인 정보를 입력해야 합니다.',
  [Phrase.StatusTitleNotAuthenticated]: '로그인 실패',
  [Phrase.StatusDescrNotAuthenticated]: '로그인에 실패했습니다. 계정 정보가 올바른지 확인하세요.',
  [Phrase.StatusTitleNoGuild]: '서버 없음',
  [Phrase.StatusDescrNoGuild]: '로그인은 성공했지만 선택한 서버가 없습니다.',
  [Phrase.StatusTitleNotAuthorized]: '접근 권한 없음',
  [Phrase.StatusDescrNotAuthorized]: '로그인은 성공했지만 선택한 서버에 접근할 권한이 없습니다.',
  [Phrase.FirstTimeSetupDescription]: '사용자가 처음으로 앱을 실행한 경우입니다.',
  [Phrase.AutoSelectEncoderTooltip]: '사용 가능한 옵션 중 합리적인 인코더를 자동으로 선택합니다. 대부분의 사용자에게 적합합니다.',
  [Phrase.CloudRefreshGuildTooltip]: '사용 가능한 서버 목록을 새로 고칩니다.',
  [Phrase.SourceSnappingSwitchText]: '맞춤 정렬',
  [Phrase.SourceSnappingSwitchTooltip]: '맞춤 정렬 기능을 켜거나 끕니다.',
  [Phrase.ResetOverlayButtonText]: '오버레이 초기화',
  [Phrase.ResetGameButtonText]: '게임 창 자동 맞춤',
  [Phrase.GameWindowLabel]: '게임 창',
  [Phrase.OverlayLabel]: '오버레이 창',
  [Phrase.AddSpeakerButtonText]: '스피커',
  [Phrase.AddMicrophoneButtonText]: '마이크',
  [Phrase.AddApplicationButtonText]: '애플리케이션',
  [Phrase.NoAudioSourcesText]: '오디오를 녹음할 소스를 추가하세요.',
  [Phrase.SelectADevice]: '장치를 선택하세요...',
  [Phrase.SelectAnApplication]: '응용 프로그램을 선택하세요...',
  [Phrase.BulkUploadButtonTooltip]: '선택한 모든 기록을 디스크에서 클라우드로 업로드합니다.',
  [Phrase.BulkDownloadButtonTooltip]: '선택한 모든 기록을 클라우드에서 디스크로 다운로드합니다.',
  [Phrase.BulkUploadDialogText]: '선택한 모든 기록의 클라우드 업로드가 대기열에 추가됩니다. 완료까지 오랜 시간이 소요될 수 있습니다. 진행 상황은 좌측 상단의 상태 배너를 통해 확인할 수 있습니다',
  [Phrase.BulkDownloadDialogText]: '선택한 모든 기록을 클라우드에서 다운로드 대기열에 추가됩니다. 진행 상황은 좌측 상단의 상태 배너를 통해 확인할 수 있습니다.',
  [Phrase.BulkTransferWarningText]: '완료하는 데 시간이 오래 걸릴 수 있습니다. 컴퓨터를 끄면 프로세스가 중단됩니다.',
  [Phrase.UploadButtonText]: '업로드 대기열 추가',
  [Phrase.DownloadButtonText]: '다운로드 대기열 추가',
  [Phrase.ChatTypeMessageText]: '댓글 추가… 타임스탬프는 MM:SS 형식을 사용하세요.',
  [Phrase.ChatUploadToCloudText]: '비디오 채팅을 사용하려면 클라우드에 업로드하세요.',
  [Phrase.ChatNoMessagesText]: '표시할 메시지가 없습니다.',
  [Phrase.ChatErrorLoadingText]: '채팅 메시지를 불러오는 중 오류가 발생했습니다.',
  [Phrase.ChatUserText1]: '채팅을 사용하려면, 이 채팅을 볼 수 있는 길드 구성원에게 사용자 이름이 공개되는 것에 동의해야 합니다.',
  [Phrase.ChatUserText2]: '이메일 주소가 노출되지 않도록 하려면, 다음 사이트에서 사용자 이름을 직접 설정할 수 있습니다: ',
  [Phrase.ChatUserText3]: ', 그런 다음 앱 설정에서 사용자 이름을 업데이트하세요.',
  [Phrase.ChatUserText4]: '다음 이름으로 채팅하기',
  [Phrase.ChatForClipsComingSoon]: '클립용 채팅 기능이 곧 제공됩니다.',
  [Phrase.ClassicPtrLogPathDescription]: '클래식 PTR 설치의 월드 오브 워크래프트 로그 폴더 위치, 예: "D:\\World of Warcraft\\_classic_ptr_\\Logs".',
  [Phrase.RecordClassicPtrDescription]: '클래식 PTR을 기록할지 여부. 이 기능은 블리자드의 PTR 전투 로그 호환성 유지 여부에 따라 달라질 수 있어 동작이 불안정할 수 있습니다.',
  [Phrase.RecordClassicPtrLabel]: '클래식 PTR 기록',
  [Phrase.ClassicPtrLogPathLabel]: '클래식 PTR 로그 경로',
  [Phrase.InvalidClassicPtrLogPathText]: '유효하지 않은 클래식 PTR 로그 경로입니다.',
  [Phrase.ClassicPtr]: '클래식 PTR',
  [Phrase.InvalidClassicPtrLogPath]: '유효하지 않은 클래식 PTR 로그 경로입니다.',
  [Phrase.PatreonButtonLabel]: 'Patreon 구독하기',
};

export default KOREAN;
